[package]
name = "pyhmeasure"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmeasure = "0.0.3"
pyo3 = "0.18.2"

[lib]
name = "pyhmeasure"